name: 'Alpine Semantic Releaser'
description: 'Run semantic-release on a repo'
branding:
  color: purple
  icon: box
inputs:
  github-token:
    description: 'Github token for pushing releases'
    required: true
    default: ''
  plugins:
    description: 'Space separated semantic-release plugins to install'
    required: false
    default: ''
outputs:
  released-version:
    description: 'The version that was released (empty if no release occured)'
  released-version-number:
    description: 'The version number (without a leading v) that was released (empty if no release occured)'
runs:
  using: 'docker'
  image: ./Dockerfile
  entrypoint: '/main.sh'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    PLUGINS: ${{ inputs.plugins }}
