name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: semantic-release
        id: semantic-release
        uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
      - name: Publish to Docker Registry
        if: steps.semantic-release.outputs.released-version-number != ''
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: rdaniels6813/semantic-release-alpine
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.semantic-release.outputs.released-version-number }}"
      - name: Publish to Github Registry
        if: steps.semantic-release.outputs.released-version-number != ''
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: rdaniels6813/semantic-release-alpine
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          tags: "latest,${{ steps.semantic-release.outputs.released-version-number }}"
